#!/usr/bin/env bash
# =============================================================================
# MO7 staging host bootstrap (Phase 31)
# =============================================================================
# Creates a staging host from scratch: directory contract, non-secret
# deployment contract (`etc/staging.env`), harness TLS material, non-production
# credentials, the release virtualenv, and the release artifact in
# `releases/<release-id>/`. Every step maps to a repository mechanism or to the
# supervisor's own commands — there is no magic step.
#
# Usage:
#   staging_bootstrap.sh <path-to-wheel> [--force]
#
# Afterwards: `bin/staging.sh init-config && bin/staging.sh deploy &&
# bin/staging.sh start && python3 harness/staging_validate.py --provision`.
#
# The persistent layer (`home/`) is never touched: re-running bootstrap on an
# existing host only rewrites the app layer unless --force is given.
# =============================================================================
set -euo pipefail

HARNESS_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAGING_ROOT="${STAGING_ROOT:-/home/user/mo7-staging}"
WHEEL="${1:-}"
FORCE="${2:-}"

if [ -z "$WHEEL" ] || [ ! -f "$WHEEL" ]; then
  echo "usage: staging_bootstrap.sh <path-to-wheel> [--force]" >&2
  exit 2
fi

VERSION="$(basename "$WHEEL" | sed -E 's/^deeptutor-([0-9.]+)-py3-none-any\.whl$/\1/')"
[ "$VERSION" != "$(basename "$WHEEL")" ] || { echo "FATAL: unexpected wheel name: $WHEEL" >&2; exit 2; }

COMMIT="$(git -C "$HARNESS_SRC/../.." rev-parse HEAD)"
RELEASE_ID="$VERSION-$(printf '%s' "$COMMIT" | cut -c1-7)"
ARTIFACT="$(basename "$WHEEL")"
ARTIFACT_SHA256="$(sha256sum "$WHEEL" | awk '{print $1}')"
PUBLIC_ORIGIN="${STAGING_PUBLIC_ORIGIN:-https://3982-${E2B_SANDBOX_ID:?E2B_SANDBOX_ID is required for the public origin}.e2b.app}"

BACKEND_PORT="${STAGING_BACKEND_PORT:-8101}"
FRONTEND_PORT="${STAGING_FRONTEND_PORT:-3982}"
TLS_PORT="${STAGING_TLS_PORT:-8443}"

log() { printf '%s  %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }

log "bootstrap: release=$RELEASE_ID artifact=$ARTIFACT sha256=$ARTIFACT_SHA256"
mkdir -p "$STAGING_ROOT"/{bin,etc,evidence,harness/tls,harness/artifact,home,releases/"$RELEASE_ID",run,secrets}

# --- harness + supervisor ----------------------------------------------------
install -m 0755 "$HARNESS_SRC/staging.sh" "$STAGING_ROOT/bin/staging.sh"
for file in staging_init_config.py staging_identity.py staging_session.py; do
  install -m 0644 "$HARNESS_SRC/$file" "$STAGING_ROOT/bin/$file"
done
for file in staging_http.py staging_validate.py staging_security.py staging_perf.py \
            staging_faults.py staging_fingerprint.py staging_artifact_probe.py \
            playwright.staging.config.ts ingress_tls_proxy.js uvicorn-log.json; do
  install -m 0644 "$HARNESS_SRC/$file" "$STAGING_ROOT/harness/$file"
done
install -m 0644 "$HARNESS_SRC/staging_artifact_probe.py" "$STAGING_ROOT/harness/artifact/staging_artifact_probe.py"
# The browser config lives in harness/ and resolves @playwright/test from there.
install -m 0644 "$HARNESS_SRC/staging_http.py" "$STAGING_ROOT/bin/staging_http.py"
if [ -d "$STAGING_ROOT/web-node_modules" ]; then :; fi
if [ ! -e "$STAGING_ROOT/harness/node_modules" ]; then
  ln -s "${MO7_WEB_NODE_MODULES:-/home/user/MO7/web/node_modules}" "$STAGING_ROOT/harness/node_modules"
fi

# --- TLS material for the harness ingress (self-signed by design) -------------
if [ ! -f "$STAGING_ROOT/harness/tls/ingress.crt" ] || [ "$FORCE" = "--force" ]; then
  openssl req -x509 -newkey rsa:2048 -nodes -days 30 \
    -keyout "$STAGING_ROOT/harness/tls/ingress.key" \
    -out "$STAGING_ROOT/harness/tls/ingress.crt" \
    -subj "/CN=MO7 staging harness ingress" \
    -addext "subjectAltName=DNS:localhost,DNS:${PUBLIC_ORIGIN#https://},IP:127.0.0.1,IP:169.254.0.21" 2>/dev/null
  log "generated harness TLS material (SAN: localhost, ${PUBLIC_ORIGIN#https://}, 127.0.0.1, 169.254.0.21)"
fi
chmod 0700 "$STAGING_ROOT/harness/tls"

# --- non-secret deployment contract ------------------------------------------
cat >"$STAGING_ROOT/etc/staging.env" <<ENV
# MO7 staging deployment contract — non-secret. Single source of truth for the
# deployment's identity, paths and bindings. Generated by staging_bootstrap.sh.
STAGING_ENVIRONMENT=staging
STAGING_RELEASE_ID=$RELEASE_ID
STAGING_SOURCE_COMMIT=$COMMIT
STAGING_VERSION=$VERSION
STAGING_ARTIFACT=$ARTIFACT
STAGING_ARTIFACT_SHA256=$ARTIFACT_SHA256
STAGING_WHEEL=$STAGING_ROOT/releases/$RELEASE_ID/$ARTIFACT
STAGING_ROOT=$STAGING_ROOT
STAGING_HOME=$STAGING_ROOT/home
STAGING_VENV=$STAGING_ROOT/venv
STAGING_RUN=$STAGING_ROOT/run
STAGING_EVIDENCE=$STAGING_ROOT/evidence
STAGING_BACKEND_HOST=127.0.0.1
STAGING_BACKEND_PORT=$BACKEND_PORT
STAGING_FRONTEND_HOST=0.0.0.0
STAGING_FRONTEND_PORT=$FRONTEND_PORT
STAGING_TLS_PORT=$TLS_PORT
STAGING_PUBLIC_ORIGIN=$PUBLIC_ORIGIN
STAGING_TLS_ORIGIN=https://127.0.0.1:$TLS_PORT
ENV
chmod 0644 "$STAGING_ROOT/etc/staging.env"
log "wrote $STAGING_ROOT/etc/staging.env (public origin $PUBLIC_ORIGIN)"

# --- release artifact --------------------------------------------------------
install -m 0644 "$WHEEL" "$STAGING_ROOT/releases/$RELEASE_ID/$ARTIFACT"
printf '%s\n' "$ARTIFACT_SHA256" >"$STAGING_ROOT/releases/$RELEASE_ID/wheel.sha256"

# --- non-production credentials (generated, never committed) -----------------
if [ ! -f "$STAGING_ROOT/secrets/staging-credentials.json" ] || [ "$FORCE" = "--force" ]; then
  python3 - "$STAGING_ROOT/secrets/staging-credentials.json" <<'PY'
import json, secrets, sys
path = sys.argv[1]
accounts = {
    "admin": "staging-admin",
    "tenant_a": "staging-tenant-a",
    "tenant_b": "staging-tenant-b",
}
payload = {
    key: {"username": username, "password": secrets.token_urlsafe(18)}
    for key, username in accounts.items()
}
payload["note"] = ("Non-production staging credentials. Generated by "
                   "staging_bootstrap.sh; never committed and never served.")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(payload, handle, indent=2)
PY
  chmod 0600 "$STAGING_ROOT/secrets/staging-credentials.json"
  log "generated non-production staging credentials (mode 0600)"
fi

# --- release virtualenv ------------------------------------------------------
if [ ! -x "$STAGING_ROOT/venv/bin/python" ] || [ "$FORCE" = "--force" ]; then
  python3 -m venv "$STAGING_ROOT/venv"
  log "created staging virtualenv"
fi
"$STAGING_ROOT/venv/bin/pip" install -q --upgrade pip >/dev/null 2>&1 || true
"$STAGING_ROOT/venv/bin/pip" install -q "$STAGING_ROOT/releases/$RELEASE_ID/$ARTIFACT" \
  >>"$STAGING_ROOT/evidence/pip-install.log" 2>&1
log "installed $ARTIFACT into the staging virtualenv"

log "bootstrap complete: next is 'bin/staging.sh init-config && bin/staging.sh deploy && bin/staging.sh start'"
